name: Publish to PyPI
on:
  # Позволяет запускать flow вручную
  workflow_dispatch:

  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and publish to pypi
        # С более ранними версиями больше не работает
        uses: JRubics/poetry-publish@v2.1
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
